### ISSUE TITLE
Support for Anaconda 4.3.1 for Python 3.6

### ISSUE THREAD

**Issue by ndefreitas** [thmttch/chef-continuum-anaconda#23]
Will this work with the current Anaconda 4.3.1?

**Comment by thmttch** [comment]
@bdd4329 Was good enough to submit a patch for 4.4.0 (here)[https://github.com/thmttch/chef-continuum-anaconda/pull/24], which has just been merged. If you want to do the same and get the SHAs for 4.3.1, please open a patch! (Assuming no major changes in the installer...?)

**Comment by thmttch** [comment]
Closing: resolved up to Anaconda 5.0. Thanks!
